<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxy751x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxy751x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxy751x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxy751x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxy751x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pxy751x',
    'container.build_id' => 'b46b55d0',
    'container.build_time' => 1669663413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxy751x');
