<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJh0HHrw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJh0HHrw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJh0HHrw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJh0HHrw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJh0HHrw\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jh0HHrw',
    'container.build_id' => 'ea87e9aa',
    'container.build_time' => 1669318870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJh0HHrw');
